name = "Sculk Modpack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3242cb4fd9f24aac8f390ef58773eec17572ddcf74e226514158f56126acf5ae"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.97"
