name = "Sculk Modpack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebe459cca8952ca19c87897ff2b1b3a747219d179feb53c563ce8b115179822c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.97"
