name = "Sculk Modpack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c3fd4cc0bdfe622b7e613d423df01926c2d606a7c73256374a786bc45bafb5d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.97"
